// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3po6SKZWQuU3CYm6w8eTLIntWOTjuToY',
    appId: '1:827011803350:web:b8e847b00a947eec4ac177',
    messagingSenderId: '827011803350',
    projectId: 'regluc-ab13f',
    authDomain: 'regluc-ab13f.firebaseapp.com',
    databaseURL: 'https://regluc-ab13f-default-rtdb.firebaseio.com',
    storageBucket: 'regluc-ab13f.appspot.com',
    measurementId: 'G-2K1MG0LX4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNxSdl1pqoyIPoh3pEuL0akHIVwbR5w4',
    appId: '1:827011803350:android:cea1343fd5b21d1f4ac177',
    messagingSenderId: '827011803350',
    projectId: 'regluc-ab13f',
    databaseURL: 'https://regluc-ab13f-default-rtdb.firebaseio.com',
    storageBucket: 'regluc-ab13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZ978OQHotCeNumazt4A-FSoqW0F457M',
    appId: '1:827011803350:ios:87f00be92251147f4ac177',
    messagingSenderId: '827011803350',
    projectId: 'regluc-ab13f',
    databaseURL: 'https://regluc-ab13f-default-rtdb.firebaseio.com',
    storageBucket: 'regluc-ab13f.appspot.com',
    iosClientId: '827011803350-ls1k6ol40lhjrh5fftd79olcnagf2ho5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZ978OQHotCeNumazt4A-FSoqW0F457M',
    appId: '1:827011803350:ios:9d5b476c8f507e8b4ac177',
    messagingSenderId: '827011803350',
    projectId: 'regluc-ab13f',
    databaseURL: 'https://regluc-ab13f-default-rtdb.firebaseio.com',
    storageBucket: 'regluc-ab13f.appspot.com',
    iosClientId: '827011803350-1md3n9q7pd0veudlk3ma9316p9qb5og8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTt.RunnerTests',
  );
}
